### ISSUE TITLE
Illegal URL

### ISSUE THREAD

**Issue by Leney** [TrustWallet/trust-wallet-android-source#34]
Just open it and crash 

Caused by: java.lang.IllegalArgumentException: Illegal URL: 
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:454)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.buildApiClient(TrustWalletTickerService.java:38)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.<init>(TrustWalletTickerService.java:33)
        at com.wallet.crypto.trustapp.di.RepositoriesModule.provideTickerService(RepositoriesModule.java:55)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:34)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:35)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:11)

**Comment by ngotuannghia** [comment]
Hello
Did you resolve this issue? 
And why close this issue without any reason?

**Comment by Leney** [comment]
> Hello
> Did you resolve this issue?
> And why close this issue without any reason?

download ios lib, found TRUST_API_URL  this --->> https://public.trustwalletapp.com
