### ISSUE TITLE
FATAL EXCEPTION can't open the app,and why?

### ISSUE THREAD

**Issue by kenneth** [TrustWallet/trust-wallet-android-source#43]
```
2019-05-01 23:26:49.173 12099-12099/com.random.pickyourown E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.random.pickyourown, PID: 12099
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.random.pickyourown/com.wallet.crypto.trustapp.ui.SplashActivity}: java.lang.IllegalArgumentException: Illegal URL: 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.IllegalArgumentException: Illegal URL: 
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:454)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.buildApiClient(TrustWalletTickerService.java:38)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.<init>(TrustWalletTickerService.java:33)
        at com.wallet.crypto.trustapp.di.RepositoriesModule.provideTickerService(RepositoriesModule.java:55)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:34)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:35)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideWalletRepositoryFactory.get(RepositoriesModule_ProvideWalletRepositoryFactory.java:50)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideWalletRepositoryFactory.get(RepositoriesModule_ProvideWalletRepositoryFactory.java:13)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideFetchWalletInteractFactory.get(SplashModule_ProvideFetchWalletInteractFactory.java:27)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideFetchWalletInteractFactory.get(SplashModule_ProvideFetchWalletInteractFactory.java:10)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideSplashViewModelFactoryFactory.get(SplashModule_ProvideSplashViewModelFactoryFactory.java:27)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideSplashViewModelFactoryFactory.get(SplashModule_ProvideSplashViewModelFactoryFactory.java:10)
        at com.wallet.crypto.trustapp.ui.SplashActivity_MembersInjector.injectMembers(SplashActivity_MembersInjector.java:27)
        at com.wallet.crypto.trustapp.ui.SplashActivity_MembersInjector.injectMembers(SplashActivity_MembersInjector.java:8)
        at com.wallet.crypto.trustapp.di.DaggerAppComponent$SplashActivitySubcomponentImpl.inject(DaggerAppComponent.java:549)
        at com.wallet.crypto.trustapp.di.DaggerAppComponent$SplashActivitySubcomponentImpl.inject(DaggerAppComponent.java:519)
        at dagger.android.DispatchingAndroidInjector.maybeInject(DispatchingAndroidInjector.java:83)
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:104)
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:61)
        at com.wallet.crypto.trustapp.ui.SplashActivity.onCreate(SplashActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
2019-05-01 23:26:49.173 12099-12099/com.random.pickyourown E/AndroidRuntime: 	... 9 more
2019-05-01 23:26:49.185 12099-12099/com.random.pickyourown I/Process: Sending signal. PID: 12099 SIG: 9
```

**Comment by NTT-TNN** [comment]
update /service/TrustWalletTickerService.java 
line 23: 
    private static final String TRUST_API_URL = "https://public.trustwalletapp.com";
insteal
    private static final String TRUST_API_URL = "";

**Comment by kenneth** [comment]
@NTT-TNN  I have run success,but the source is old .No the newest version.
just have ethererum wallet,not the HD wallet

**Comment by kenneth** [comment]
> @NTT-TNN I have run success,but the source is old .No the newest version.
> just have ethererum wallet,not the HD wallet
