### ISSUE TITLE
Running crashes

### ISSUE THREAD

**Issue by bayshier** [TrustWallet/trust-wallet-android-source#44]
2019-05-09 20:38:21.441 30370-30370/com.random.pickyourown E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.random.pickyourown, PID: 30370
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.random.pickyourown/com.wallet.crypto.trustapp.ui.SplashActivity}: java.lang.IllegalArgumentException: Illegal URL: 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.IllegalArgumentException: Illegal URL: 
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:454)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.buildApiClient(TrustWalletTickerService.java:38)
        at com.wallet.crypto.trustapp.service.TrustWalletTickerService.<init>(TrustWalletTickerService.java:33)
        at com.wallet.crypto.trustapp.di.RepositoriesModule.provideTickerService(RepositoriesModule.java:55)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:34)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideTickerServiceFactory.get(RepositoriesModule_ProvideTickerServiceFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:35)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.get(RepositoriesModule_ProvideEthereumNetworkRepositoryFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideWalletRepositoryFactory.get(RepositoriesModule_ProvideWalletRepositoryFactory.java:50)
        at com.wallet.crypto.trustapp.di.RepositoriesModule_ProvideWalletRepositoryFactory.get(RepositoriesModule_ProvideWalletRepositoryFactory.java:13)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideFetchWalletInteractFactory.get(SplashModule_ProvideFetchWalletInteractFactory.java:27)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideFetchWalletInteractFactory.get(SplashModule_ProvideFetchWalletInteractFactory.java:10)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideSplashViewModelFactoryFactory.get(SplashModule_ProvideSplashViewModelFactoryFactory.java:27)
        at com.wallet.crypto.trustapp.di.SplashModule_ProvideSplashViewModelFactoryFactory.get(SplashModule_ProvideSplashViewModelFactoryFactory.java:10)
        at com.wallet.crypto.trustapp.ui.SplashActivity_MembersInjector.injectMembers(SplashActivity_MembersInjector.java:27)
        at com.wallet.crypto.trustapp.ui.SplashActivity_MembersInjector.injectMembers(SplashActivity_MembersInjector.java:8)
        at com.wallet.crypto.trustapp.di.DaggerAppComponent$SplashActivitySubcomponentImpl.inject(DaggerAppComponent.java:549)
        at com.wallet.crypto.trustapp.di.DaggerAppComponent$SplashActivitySubcomponentImpl.inject(DaggerAppComponent.java:519)
        at dagger.android.DispatchingAndroidInjector.maybeInject(DispatchingAndroidInjector.java:83)
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:104)
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:61)
2019-05-09 20:38:21.442 30370-30370/com.random.pickyourown E/AndroidRuntime:     at com.wallet.crypto.trustapp.ui.SplashActivity.onCreate(SplashActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
        	... 11 more

**Comment by rectinajh** [comment]
i build the release version code,but failed,anyone help?
